version: '3.7'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.22
    hostname: jaeger
    restart: always
    ports:
      - '16686:16686' # Jaeger UI
      - '14250:14250' # gRPC
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '9411:9411'
  
  webnetcore:
    build: .\src    
    environment: 
      Jaeger__Host: jaeger
      Jaeger__Port: 6831
      OTelExporter__Host: http://otelcol:4317
    ports:
      - '5000:80'
    depends_on:
      - jaeger

  # OpenTelemetry Collector
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.77.0
    container_name: otel-col
    deploy:
      resources:
        limits:
          memory: 125M
    restart: unless-stopped
    command: [ "--config=/etc/otelcol-config.yml" ]
    volumes:
      - ./otelcollector/otelcol-config.yml:/etc/otelcol-config.yml
    ports:
      - "13133:13133"   # health_check extension
      - "4317:4317"     # OTLP receiver over gRPC  (default value)
      - "4318:4318"     # OTLP receiver over HTTP  (default value)
    depends_on:
      - jaeger
